//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsService
{
    using EasyAssetManagerCore.Model.CommonModel;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmsService.SmsManagerSoap")]
    public interface SmsManagerSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsService.SendSmsResponse> SendSmsAsync(SmsService.SendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendCustomSms", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsService.SendCustomSmsResponse> SendCustomSmsAsync(SmsService.SendCustomSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendBulkSms", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsService.SendBulkSmsResponse> SendBulkSmsAsync(SmsService.SendBulkSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendCustomBulkSms", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsService.SendCustomBulkSmsResponse> SendCustomBulkSmsAsync(SmsService.SendCustomBulkSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSmsStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsService.GetSmsStatusResponse> GetSmsStatusAsync(SmsService.GetSmsStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSms", Namespace="http://tempuri.org/", Order=0)]
        public SmsService.SendSmsRequestBody Body;
        
        public SendSmsRequest()
        {
        }
        
        public SendSmsRequest(SmsService.SendSmsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sms_tmpl_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mobile_no;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sms;
        
        public SendSmsRequestBody()
        {
        }
        
        public SendSmsRequestBody(string user_id, string password, string sms_tmpl_id, string mobile_no, string sms)
        {
            this.user_id = user_id;
            this.password = password;
            this.sms_tmpl_id = sms_tmpl_id;
            this.mobile_no = mobile_no;
            this.sms = sms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmsService.SendSmsResponseBody Body;
        
        public SendSmsResponse()
        {
        }
        
        public SendSmsResponse(SmsService.SendSmsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SmsService.ArrayOfString SendSmsResult;
        
        public SendSmsResponseBody()
        {
        }
        
        public SendSmsResponseBody(SmsService.ArrayOfString SendSmsResult)
        {
            this.SendSmsResult = SendSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendCustomSmsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendCustomSms", Namespace="http://tempuri.org/", Order=0)]
        public SmsService.SendCustomSmsRequestBody Body;
        
        public SendCustomSmsRequest()
        {
        }
        
        public SendCustomSmsRequest(SmsService.SendCustomSmsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendCustomSmsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sms_type_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sms_tmpl_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string mobile_no;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sms;
        
        public SendCustomSmsRequestBody()
        {
        }
        
        public SendCustomSmsRequestBody(string user_id, string password, string sms_type_id, string sms_tmpl_id, string mobile_no, string sms)
        {
            this.user_id = user_id;
            this.password = password;
            this.sms_type_id = sms_type_id;
            this.sms_tmpl_id = sms_tmpl_id;
            this.mobile_no = mobile_no;
            this.sms = sms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendCustomSmsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendCustomSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmsService.SendCustomSmsResponseBody Body;
        
        public SendCustomSmsResponse()
        {
        }
        
        public SendCustomSmsResponse(SmsService.SendCustomSmsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendCustomSmsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SmsService.ArrayOfString SendCustomSmsResult;
        
        public SendCustomSmsResponseBody()
        {
        }
        
        public SendCustomSmsResponseBody(SmsService.ArrayOfString SendCustomSmsResult)
        {
            this.SendCustomSmsResult = SendCustomSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendBulkSmsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendBulkSms", Namespace="http://tempuri.org/", Order=0)]
        public SmsService.SendBulkSmsRequestBody Body;
        
        public SendBulkSmsRequest()
        {
        }
        
        public SendBulkSmsRequest(SmsService.SendBulkSmsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendBulkSmsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sms_tmpl_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mobile_no;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sms;
        
        public SendBulkSmsRequestBody()
        {
        }
        
        public SendBulkSmsRequestBody(string user_id, string password, string sms_tmpl_id, string mobile_no, string sms)
        {
            this.user_id = user_id;
            this.password = password;
            this.sms_tmpl_id = sms_tmpl_id;
            this.mobile_no = mobile_no;
            this.sms = sms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendBulkSmsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendBulkSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmsService.SendBulkSmsResponseBody Body;
        
        public SendBulkSmsResponse()
        {
        }
        
        public SendBulkSmsResponse(SmsService.SendBulkSmsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendBulkSmsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SmsService.ArrayOfString SendBulkSmsResult;
        
        public SendBulkSmsResponseBody()
        {
        }
        
        public SendBulkSmsResponseBody(SmsService.ArrayOfString SendBulkSmsResult)
        {
            this.SendBulkSmsResult = SendBulkSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendCustomBulkSmsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendCustomBulkSms", Namespace="http://tempuri.org/", Order=0)]
        public SmsService.SendCustomBulkSmsRequestBody Body;
        
        public SendCustomBulkSmsRequest()
        {
        }
        
        public SendCustomBulkSmsRequest(SmsService.SendCustomBulkSmsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendCustomBulkSmsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sms_type_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sms_tmpl_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string mobile_no;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sms;
        
        public SendCustomBulkSmsRequestBody()
        {
        }
        
        public SendCustomBulkSmsRequestBody(string user_id, string password, string sms_type_id, string sms_tmpl_id, string mobile_no, string sms)
        {
            this.user_id = user_id;
            this.password = password;
            this.sms_type_id = sms_type_id;
            this.sms_tmpl_id = sms_tmpl_id;
            this.mobile_no = mobile_no;
            this.sms = sms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendCustomBulkSmsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendCustomBulkSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmsService.SendCustomBulkSmsResponseBody Body;
        
        public SendCustomBulkSmsResponse()
        {
        }
        
        public SendCustomBulkSmsResponse(SmsService.SendCustomBulkSmsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendCustomBulkSmsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SmsService.ArrayOfString SendCustomBulkSmsResult;
        
        public SendCustomBulkSmsResponseBody()
        {
        }
        
        public SendCustomBulkSmsResponseBody(SmsService.ArrayOfString SendCustomBulkSmsResult)
        {
            this.SendCustomBulkSmsResult = SendCustomBulkSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSmsStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSmsStatus", Namespace="http://tempuri.org/", Order=0)]
        public SmsService.GetSmsStatusRequestBody Body;
        
        public GetSmsStatusRequest()
        {
        }
        
        public GetSmsStatusRequest(SmsService.GetSmsStatusRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSmsStatusRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sms_type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sms_id;
        
        public GetSmsStatusRequestBody()
        {
        }
        
        public GetSmsStatusRequestBody(string user_id, string password, string sms_type, string sms_id)
        {
            this.user_id = user_id;
            this.password = password;
            this.sms_type = sms_type;
            this.sms_id = sms_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSmsStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSmsStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmsService.GetSmsStatusResponseBody Body;
        
        public GetSmsStatusResponse()
        {
        }
        
        public GetSmsStatusResponse(SmsService.GetSmsStatusResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSmsStatusResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SmsService.ArrayOfString GetSmsStatusResult;
        
        public GetSmsStatusResponseBody()
        {
        }
        
        public GetSmsStatusResponseBody(SmsService.ArrayOfString GetSmsStatusResult)
        {
            this.GetSmsStatusResult = GetSmsStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface SmsManagerSoapChannel : SmsService.SmsManagerSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class SmsManagerSoapClient : System.ServiceModel.ClientBase<SmsService.SmsManagerSoap>, SmsService.SmsManagerSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SmsManagerSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SmsManagerSoapClient.GetBindingForEndpoint(endpointConfiguration), SmsManagerSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SmsManagerSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SmsManagerSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SmsManagerSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SmsManagerSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SmsManagerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsService.SendSmsResponse> SmsService.SmsManagerSoap.SendSmsAsync(SmsService.SendSmsRequest request)
        {
            return base.Channel.SendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsService.SendSmsResponse> SendSmsAsync(string user_id, string password, string sms_tmpl_id, string mobile_no, string sms)
        {
            SmsService.SendSmsRequest inValue = new SmsService.SendSmsRequest();
            inValue.Body = new SmsService.SendSmsRequestBody();
            inValue.Body.user_id = user_id;
            inValue.Body.password = password;
            inValue.Body.sms_tmpl_id = sms_tmpl_id;
            inValue.Body.mobile_no = mobile_no;
            inValue.Body.sms = sms;
            return ((SmsService.SmsManagerSoap)(this)).SendSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsService.SendCustomSmsResponse> SmsService.SmsManagerSoap.SendCustomSmsAsync(SmsService.SendCustomSmsRequest request)
        {
            return base.Channel.SendCustomSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsService.SendCustomSmsResponse> SendCustomSmsAsync(string user_id, string password, string sms_type_id, string sms_tmpl_id, string mobile_no, string sms)
        {
            SmsService.SendCustomSmsRequest inValue = new SmsService.SendCustomSmsRequest();
            inValue.Body = new SmsService.SendCustomSmsRequestBody();
            inValue.Body.user_id = user_id;
            inValue.Body.password = password;
            inValue.Body.sms_type_id = sms_type_id;
            inValue.Body.sms_tmpl_id = sms_tmpl_id;
            inValue.Body.mobile_no = mobile_no;
            inValue.Body.sms = sms;
            return ((SmsService.SmsManagerSoap)(this)).SendCustomSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsService.SendBulkSmsResponse> SmsService.SmsManagerSoap.SendBulkSmsAsync(SmsService.SendBulkSmsRequest request)
        {
            return base.Channel.SendBulkSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsService.SendBulkSmsResponse> SendBulkSmsAsync(string user_id, string password, string sms_tmpl_id, string mobile_no, string sms)
        {
            SmsService.SendBulkSmsRequest inValue = new SmsService.SendBulkSmsRequest();
            inValue.Body = new SmsService.SendBulkSmsRequestBody();
            inValue.Body.user_id = user_id;
            inValue.Body.password = password;
            inValue.Body.sms_tmpl_id = sms_tmpl_id;
            inValue.Body.mobile_no = mobile_no;
            inValue.Body.sms = sms;
            return ((SmsService.SmsManagerSoap)(this)).SendBulkSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsService.SendCustomBulkSmsResponse> SmsService.SmsManagerSoap.SendCustomBulkSmsAsync(SmsService.SendCustomBulkSmsRequest request)
        {
            return base.Channel.SendCustomBulkSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsService.SendCustomBulkSmsResponse> SendCustomBulkSmsAsync(string user_id, string password, string sms_type_id, string sms_tmpl_id, string mobile_no, string sms)
        {
            SmsService.SendCustomBulkSmsRequest inValue = new SmsService.SendCustomBulkSmsRequest();
            inValue.Body = new SmsService.SendCustomBulkSmsRequestBody();
            inValue.Body.user_id = user_id;
            inValue.Body.password = password;
            inValue.Body.sms_type_id = sms_type_id;
            inValue.Body.sms_tmpl_id = sms_tmpl_id;
            inValue.Body.mobile_no = mobile_no;
            inValue.Body.sms = sms;
            return ((SmsService.SmsManagerSoap)(this)).SendCustomBulkSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsService.GetSmsStatusResponse> SmsService.SmsManagerSoap.GetSmsStatusAsync(SmsService.GetSmsStatusRequest request)
        {
            return base.Channel.GetSmsStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsService.GetSmsStatusResponse> GetSmsStatusAsync(string user_id, string password, string sms_type, string sms_id)
        {
            SmsService.GetSmsStatusRequest inValue = new SmsService.GetSmsStatusRequest();
            inValue.Body = new SmsService.GetSmsStatusRequestBody();
            inValue.Body.user_id = user_id;
            inValue.Body.password = password;
            inValue.Body.sms_type = sms_type;
            inValue.Body.sms_id = sms_id;
            return ((SmsService.SmsManagerSoap)(this)).GetSmsStatusAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SmsManagerSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SmsManagerSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SmsManagerSoap))
            {
                return new System.ServiceModel.EndpointAddress(ApplicationConstant.SmsService);
            }
            if ((endpointConfiguration == EndpointConfiguration.SmsManagerSoap12))
            {
                return new System.ServiceModel.EndpointAddress(ApplicationConstant.SmsService);
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SmsManagerSoap,
            
            SmsManagerSoap12,
        }
    }
}
