//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EasyAssetManagerCore.Model.CommonModel;

namespace FcubService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", ConfigurationName="FcubService.FCUBSDEServiceSEI")]
    public interface FCUBSDEServiceSEI
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FcubService.SingleViewResponse> SingleViewAsync(FcubService.SingleViewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FcubService.SingleBatOpenResponse> SingleBatOpenAsync(FcubService.SingleBatOpenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FcubService.SingleNewResponse> SingleNewAsync(FcubService.SingleNewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FcubService.SingleDeleteResponse> SingleDeleteAsync(FcubService.SingleDeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FcubService.SingleAuthQueryResponse> SingleAuthQueryAsync(FcubService.SingleAuthQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FcubService.SingleAuthorizeResponse> SingleAuthorizeAsync(FcubService.SingleAuthorizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FcubService.SingleCloseResponse> SingleCloseAsync(FcubService.SingleCloseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FcubService.MultiViewResponse> MultiViewAsync(FcubService.MultiViewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FcubService.MultiBatOpenResponse> MultiBatOpenAsync(FcubService.MultiBatOpenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FcubService.MultiNewResponse> MultiNewAsync(FcubService.MultiNewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FcubService.MultiDeleteResponse> MultiDeleteAsync(FcubService.MultiDeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FcubService.MultiAuthQueryResponse> MultiAuthQueryAsync(FcubService.MultiAuthQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FcubService.MultiAuthorizeResponse> MultiAuthorizeAsync(FcubService.MultiAuthorizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FcubService.MultiCloseResponse> MultiCloseAsync(FcubService.MultiCloseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FcubService.BatchReassignResponse> BatchReassignAsync(FcubService.BatchReassignRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FcubService.BatchTotQueryResponse> BatchTotQueryAsync(FcubService.BatchTotQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FcubService.BatchTotDeleteResponse> BatchTotDeleteAsync(FcubService.BatchTotDeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FcubService.BatchTotAuthResponse> BatchTotAuthAsync(FcubService.BatchTotAuthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FcubService.BatchAuthorizeResponse> BatchAuthorizeAsync(FcubService.BatchAuthorizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FcubService.BatchAuthQryResponse> BatchAuthQryAsync(FcubService.BatchAuthQryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SingleViewRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string SingleView;
        
        public SingleViewRequest()
        {
        }
        
        public SingleViewRequest(string SingleView)
        {
            this.SingleView = SingleView;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SingleViewResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SingleViewResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string SingleViewResponse1;
        
        public SingleViewResponse()
        {
        }
        
        public SingleViewResponse(string SingleViewResponse1)
        {
            this.SingleViewResponse1 = SingleViewResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SingleBatOpenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string SingleBatOpen;
        
        public SingleBatOpenRequest()
        {
        }
        
        public SingleBatOpenRequest(string SingleBatOpen)
        {
            this.SingleBatOpen = SingleBatOpen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SingleBatOpenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SingleBatOpenResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string SingleBatOpenResponse1;
        
        public SingleBatOpenResponse()
        {
        }
        
        public SingleBatOpenResponse(string SingleBatOpenResponse1)
        {
            this.SingleBatOpenResponse1 = SingleBatOpenResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SingleNewRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string SingleNew;
        
        public SingleNewRequest()
        {
        }
        
        public SingleNewRequest(string SingleNew)
        {
            this.SingleNew = SingleNew;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SingleNewResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SingleNewResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string SingleNewResponse1;
        
        public SingleNewResponse()
        {
        }
        
        public SingleNewResponse(string SingleNewResponse1)
        {
            this.SingleNewResponse1 = SingleNewResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SingleDeleteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string SingleDelete;
        
        public SingleDeleteRequest()
        {
        }
        
        public SingleDeleteRequest(string SingleDelete)
        {
            this.SingleDelete = SingleDelete;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SingleDeleteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SingleDeleteResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string SingleDeleteResponse1;
        
        public SingleDeleteResponse()
        {
        }
        
        public SingleDeleteResponse(string SingleDeleteResponse1)
        {
            this.SingleDeleteResponse1 = SingleDeleteResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SingleAuthQueryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string SingleAuthQuery;
        
        public SingleAuthQueryRequest()
        {
        }
        
        public SingleAuthQueryRequest(string SingleAuthQuery)
        {
            this.SingleAuthQuery = SingleAuthQuery;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SingleAuthQueryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SingleAuthQueryResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string SingleAuthQueryResponse1;
        
        public SingleAuthQueryResponse()
        {
        }
        
        public SingleAuthQueryResponse(string SingleAuthQueryResponse1)
        {
            this.SingleAuthQueryResponse1 = SingleAuthQueryResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SingleAuthorizeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string SingleAuthorize;
        
        public SingleAuthorizeRequest()
        {
        }
        
        public SingleAuthorizeRequest(string SingleAuthorize)
        {
            this.SingleAuthorize = SingleAuthorize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SingleAuthorizeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SingleAuthorizeResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string SingleAuthorizeResponse1;
        
        public SingleAuthorizeResponse()
        {
        }
        
        public SingleAuthorizeResponse(string SingleAuthorizeResponse1)
        {
            this.SingleAuthorizeResponse1 = SingleAuthorizeResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SingleCloseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string SingleClose;
        
        public SingleCloseRequest()
        {
        }
        
        public SingleCloseRequest(string SingleClose)
        {
            this.SingleClose = SingleClose;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SingleCloseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SingleCloseResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string SingleCloseResponse1;
        
        public SingleCloseResponse()
        {
        }
        
        public SingleCloseResponse(string SingleCloseResponse1)
        {
            this.SingleCloseResponse1 = SingleCloseResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiViewRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string MultiView;
        
        public MultiViewRequest()
        {
        }
        
        public MultiViewRequest(string MultiView)
        {
            this.MultiView = MultiView;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiViewResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultiViewResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string MultiViewResponse1;
        
        public MultiViewResponse()
        {
        }
        
        public MultiViewResponse(string MultiViewResponse1)
        {
            this.MultiViewResponse1 = MultiViewResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiBatOpenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string MultiBatOpen;
        
        public MultiBatOpenRequest()
        {
        }
        
        public MultiBatOpenRequest(string MultiBatOpen)
        {
            this.MultiBatOpen = MultiBatOpen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiBatOpenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultiBatOpenResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string MultiBatOpenResponse1;
        
        public MultiBatOpenResponse()
        {
        }
        
        public MultiBatOpenResponse(string MultiBatOpenResponse1)
        {
            this.MultiBatOpenResponse1 = MultiBatOpenResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiNewRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string MultiNew;
        
        public MultiNewRequest()
        {
        }
        
        public MultiNewRequest(string MultiNew)
        {
            this.MultiNew = MultiNew;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiNewResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultiNewResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string MultiNewResponse1;
        
        public MultiNewResponse()
        {
        }
        
        public MultiNewResponse(string MultiNewResponse1)
        {
            this.MultiNewResponse1 = MultiNewResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiDeleteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string MultiDelete;
        
        public MultiDeleteRequest()
        {
        }
        
        public MultiDeleteRequest(string MultiDelete)
        {
            this.MultiDelete = MultiDelete;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiDeleteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultiDeleteResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string MultiDeleteResponse1;
        
        public MultiDeleteResponse()
        {
        }
        
        public MultiDeleteResponse(string MultiDeleteResponse1)
        {
            this.MultiDeleteResponse1 = MultiDeleteResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiAuthQueryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string MultiAuthQuery;
        
        public MultiAuthQueryRequest()
        {
        }
        
        public MultiAuthQueryRequest(string MultiAuthQuery)
        {
            this.MultiAuthQuery = MultiAuthQuery;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiAuthQueryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultiAuthQueryResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string MultiAuthQueryResponse1;
        
        public MultiAuthQueryResponse()
        {
        }
        
        public MultiAuthQueryResponse(string MultiAuthQueryResponse1)
        {
            this.MultiAuthQueryResponse1 = MultiAuthQueryResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiAuthorizeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string MultiAuthorize;
        
        public MultiAuthorizeRequest()
        {
        }
        
        public MultiAuthorizeRequest(string MultiAuthorize)
        {
            this.MultiAuthorize = MultiAuthorize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiAuthorizeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultiAuthorizeResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string MultiAuthorizeResponse1;
        
        public MultiAuthorizeResponse()
        {
        }
        
        public MultiAuthorizeResponse(string MultiAuthorizeResponse1)
        {
            this.MultiAuthorizeResponse1 = MultiAuthorizeResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiCloseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string MultiClose;
        
        public MultiCloseRequest()
        {
        }
        
        public MultiCloseRequest(string MultiClose)
        {
            this.MultiClose = MultiClose;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiCloseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultiCloseResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string MultiCloseResponse1;
        
        public MultiCloseResponse()
        {
        }
        
        public MultiCloseResponse(string MultiCloseResponse1)
        {
            this.MultiCloseResponse1 = MultiCloseResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchReassignRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string BatchReassign;
        
        public BatchReassignRequest()
        {
        }
        
        public BatchReassignRequest(string BatchReassign)
        {
            this.BatchReassign = BatchReassign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchReassignResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchReassignResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string BatchReassignResponse1;
        
        public BatchReassignResponse()
        {
        }
        
        public BatchReassignResponse(string BatchReassignResponse1)
        {
            this.BatchReassignResponse1 = BatchReassignResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchTotQueryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string BatchTotQuery;
        
        public BatchTotQueryRequest()
        {
        }
        
        public BatchTotQueryRequest(string BatchTotQuery)
        {
            this.BatchTotQuery = BatchTotQuery;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchTotQueryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchTotQueryResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string BatchTotQueryResponse1;
        
        public BatchTotQueryResponse()
        {
        }
        
        public BatchTotQueryResponse(string BatchTotQueryResponse1)
        {
            this.BatchTotQueryResponse1 = BatchTotQueryResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchTotDeleteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string BatchTotDelete;
        
        public BatchTotDeleteRequest()
        {
        }
        
        public BatchTotDeleteRequest(string BatchTotDelete)
        {
            this.BatchTotDelete = BatchTotDelete;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchTotDeleteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchTotDeleteResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string BatchTotDeleteResponse1;
        
        public BatchTotDeleteResponse()
        {
        }
        
        public BatchTotDeleteResponse(string BatchTotDeleteResponse1)
        {
            this.BatchTotDeleteResponse1 = BatchTotDeleteResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchTotAuthRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string BatchTotAuth;
        
        public BatchTotAuthRequest()
        {
        }
        
        public BatchTotAuthRequest(string BatchTotAuth)
        {
            this.BatchTotAuth = BatchTotAuth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchTotAuthResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchTotAuthResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string BatchTotAuthResponse1;
        
        public BatchTotAuthResponse()
        {
        }
        
        public BatchTotAuthResponse(string BatchTotAuthResponse1)
        {
            this.BatchTotAuthResponse1 = BatchTotAuthResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchAuthorizeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string BatchAuthorize;
        
        public BatchAuthorizeRequest()
        {
        }
        
        public BatchAuthorizeRequest(string BatchAuthorize)
        {
            this.BatchAuthorize = BatchAuthorize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchAuthorizeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchAuthorizeResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string BatchAuthorizeResponse1;
        
        public BatchAuthorizeResponse()
        {
        }
        
        public BatchAuthorizeResponse(string BatchAuthorizeResponse1)
        {
            this.BatchAuthorizeResponse1 = BatchAuthorizeResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchAuthQryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string BatchAuthQry;
        
        public BatchAuthQryRequest()
        {
        }
        
        public BatchAuthQryRequest(string BatchAuthQry)
        {
            this.BatchAuthQry = BatchAuthQry;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchAuthQryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchAuthQryResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string BatchAuthQryResponse1;
        
        public BatchAuthQryResponse()
        {
        }
        
        public BatchAuthQryResponse(string BatchAuthQryResponse1)
        {
            this.BatchAuthQryResponse1 = BatchAuthQryResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface FCUBSDEServiceSEIChannel : FcubService.FCUBSDEServiceSEI, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class FCUBSDEServiceSEIClient : System.ServiceModel.ClientBase<FcubService.FCUBSDEServiceSEI>, FcubService.FCUBSDEServiceSEI
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FCUBSDEServiceSEIClient() : 
                base(FCUBSDEServiceSEIClient.GetDefaultBinding(), FCUBSDEServiceSEIClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.FCUBSDEServiceSEI.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FCUBSDEServiceSEIClient(EndpointConfiguration endpointConfiguration) : 
                base(FCUBSDEServiceSEIClient.GetBindingForEndpoint(endpointConfiguration), FCUBSDEServiceSEIClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FCUBSDEServiceSEIClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FCUBSDEServiceSEIClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FCUBSDEServiceSEIClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FCUBSDEServiceSEIClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FCUBSDEServiceSEIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FcubService.SingleViewResponse> FcubService.FCUBSDEServiceSEI.SingleViewAsync(FcubService.SingleViewRequest request)
        {
            return base.Channel.SingleViewAsync(request);
        }
        
        public System.Threading.Tasks.Task<FcubService.SingleViewResponse> SingleViewAsync(string SingleView)
        {
            FcubService.SingleViewRequest inValue = new FcubService.SingleViewRequest();
            inValue.SingleView = SingleView;
            return ((FcubService.FCUBSDEServiceSEI)(this)).SingleViewAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FcubService.SingleBatOpenResponse> FcubService.FCUBSDEServiceSEI.SingleBatOpenAsync(FcubService.SingleBatOpenRequest request)
        {
            return base.Channel.SingleBatOpenAsync(request);
        }
        
        public System.Threading.Tasks.Task<FcubService.SingleBatOpenResponse> SingleBatOpenAsync(string SingleBatOpen)
        {
            FcubService.SingleBatOpenRequest inValue = new FcubService.SingleBatOpenRequest();
            inValue.SingleBatOpen = SingleBatOpen;
            return ((FcubService.FCUBSDEServiceSEI)(this)).SingleBatOpenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FcubService.SingleNewResponse> FcubService.FCUBSDEServiceSEI.SingleNewAsync(FcubService.SingleNewRequest request)
        {
            return base.Channel.SingleNewAsync(request);
        }
        
        public System.Threading.Tasks.Task<FcubService.SingleNewResponse> SingleNewAsync(string SingleNew)
        {
            FcubService.SingleNewRequest inValue = new FcubService.SingleNewRequest();
            inValue.SingleNew = SingleNew;
            return ((FcubService.FCUBSDEServiceSEI)(this)).SingleNewAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FcubService.SingleDeleteResponse> FcubService.FCUBSDEServiceSEI.SingleDeleteAsync(FcubService.SingleDeleteRequest request)
        {
            return base.Channel.SingleDeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<FcubService.SingleDeleteResponse> SingleDeleteAsync(string SingleDelete)
        {
            FcubService.SingleDeleteRequest inValue = new FcubService.SingleDeleteRequest();
            inValue.SingleDelete = SingleDelete;
            return ((FcubService.FCUBSDEServiceSEI)(this)).SingleDeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FcubService.SingleAuthQueryResponse> FcubService.FCUBSDEServiceSEI.SingleAuthQueryAsync(FcubService.SingleAuthQueryRequest request)
        {
            return base.Channel.SingleAuthQueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<FcubService.SingleAuthQueryResponse> SingleAuthQueryAsync(string SingleAuthQuery)
        {
            FcubService.SingleAuthQueryRequest inValue = new FcubService.SingleAuthQueryRequest();
            inValue.SingleAuthQuery = SingleAuthQuery;
            return ((FcubService.FCUBSDEServiceSEI)(this)).SingleAuthQueryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FcubService.SingleAuthorizeResponse> FcubService.FCUBSDEServiceSEI.SingleAuthorizeAsync(FcubService.SingleAuthorizeRequest request)
        {
            return base.Channel.SingleAuthorizeAsync(request);
        }
        
        public System.Threading.Tasks.Task<FcubService.SingleAuthorizeResponse> SingleAuthorizeAsync(string SingleAuthorize)
        {
            FcubService.SingleAuthorizeRequest inValue = new FcubService.SingleAuthorizeRequest();
            inValue.SingleAuthorize = SingleAuthorize;
            return ((FcubService.FCUBSDEServiceSEI)(this)).SingleAuthorizeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FcubService.SingleCloseResponse> FcubService.FCUBSDEServiceSEI.SingleCloseAsync(FcubService.SingleCloseRequest request)
        {
            return base.Channel.SingleCloseAsync(request);
        }
        
        public System.Threading.Tasks.Task<FcubService.SingleCloseResponse> SingleCloseAsync(string SingleClose)
        {
            FcubService.SingleCloseRequest inValue = new FcubService.SingleCloseRequest();
            inValue.SingleClose = SingleClose;
            return ((FcubService.FCUBSDEServiceSEI)(this)).SingleCloseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FcubService.MultiViewResponse> FcubService.FCUBSDEServiceSEI.MultiViewAsync(FcubService.MultiViewRequest request)
        {
            return base.Channel.MultiViewAsync(request);
        }
        
        public System.Threading.Tasks.Task<FcubService.MultiViewResponse> MultiViewAsync(string MultiView)
        {
            FcubService.MultiViewRequest inValue = new FcubService.MultiViewRequest();
            inValue.MultiView = MultiView;
            return ((FcubService.FCUBSDEServiceSEI)(this)).MultiViewAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FcubService.MultiBatOpenResponse> FcubService.FCUBSDEServiceSEI.MultiBatOpenAsync(FcubService.MultiBatOpenRequest request)
        {
            return base.Channel.MultiBatOpenAsync(request);
        }
        
        public System.Threading.Tasks.Task<FcubService.MultiBatOpenResponse> MultiBatOpenAsync(string MultiBatOpen)
        {
            FcubService.MultiBatOpenRequest inValue = new FcubService.MultiBatOpenRequest();
            inValue.MultiBatOpen = MultiBatOpen;
            return ((FcubService.FCUBSDEServiceSEI)(this)).MultiBatOpenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FcubService.MultiNewResponse> FcubService.FCUBSDEServiceSEI.MultiNewAsync(FcubService.MultiNewRequest request)
        {
            return base.Channel.MultiNewAsync(request);
        }
        
        public System.Threading.Tasks.Task<FcubService.MultiNewResponse> MultiNewAsync(string MultiNew)
        {
            FcubService.MultiNewRequest inValue = new FcubService.MultiNewRequest();
            inValue.MultiNew = MultiNew;
            return ((FcubService.FCUBSDEServiceSEI)(this)).MultiNewAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FcubService.MultiDeleteResponse> FcubService.FCUBSDEServiceSEI.MultiDeleteAsync(FcubService.MultiDeleteRequest request)
        {
            return base.Channel.MultiDeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<FcubService.MultiDeleteResponse> MultiDeleteAsync(string MultiDelete)
        {
            FcubService.MultiDeleteRequest inValue = new FcubService.MultiDeleteRequest();
            inValue.MultiDelete = MultiDelete;
            return ((FcubService.FCUBSDEServiceSEI)(this)).MultiDeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FcubService.MultiAuthQueryResponse> FcubService.FCUBSDEServiceSEI.MultiAuthQueryAsync(FcubService.MultiAuthQueryRequest request)
        {
            return base.Channel.MultiAuthQueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<FcubService.MultiAuthQueryResponse> MultiAuthQueryAsync(string MultiAuthQuery)
        {
            FcubService.MultiAuthQueryRequest inValue = new FcubService.MultiAuthQueryRequest();
            inValue.MultiAuthQuery = MultiAuthQuery;
            return ((FcubService.FCUBSDEServiceSEI)(this)).MultiAuthQueryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FcubService.MultiAuthorizeResponse> FcubService.FCUBSDEServiceSEI.MultiAuthorizeAsync(FcubService.MultiAuthorizeRequest request)
        {
            return base.Channel.MultiAuthorizeAsync(request);
        }
        
        public System.Threading.Tasks.Task<FcubService.MultiAuthorizeResponse> MultiAuthorizeAsync(string MultiAuthorize)
        {
            FcubService.MultiAuthorizeRequest inValue = new FcubService.MultiAuthorizeRequest();
            inValue.MultiAuthorize = MultiAuthorize;
            return ((FcubService.FCUBSDEServiceSEI)(this)).MultiAuthorizeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FcubService.MultiCloseResponse> FcubService.FCUBSDEServiceSEI.MultiCloseAsync(FcubService.MultiCloseRequest request)
        {
            return base.Channel.MultiCloseAsync(request);
        }
        
        public System.Threading.Tasks.Task<FcubService.MultiCloseResponse> MultiCloseAsync(string MultiClose)
        {
            FcubService.MultiCloseRequest inValue = new FcubService.MultiCloseRequest();
            inValue.MultiClose = MultiClose;
            return ((FcubService.FCUBSDEServiceSEI)(this)).MultiCloseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FcubService.BatchReassignResponse> FcubService.FCUBSDEServiceSEI.BatchReassignAsync(FcubService.BatchReassignRequest request)
        {
            return base.Channel.BatchReassignAsync(request);
        }
        
        public System.Threading.Tasks.Task<FcubService.BatchReassignResponse> BatchReassignAsync(string BatchReassign)
        {
            FcubService.BatchReassignRequest inValue = new FcubService.BatchReassignRequest();
            inValue.BatchReassign = BatchReassign;
            return ((FcubService.FCUBSDEServiceSEI)(this)).BatchReassignAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FcubService.BatchTotQueryResponse> FcubService.FCUBSDEServiceSEI.BatchTotQueryAsync(FcubService.BatchTotQueryRequest request)
        {
            return base.Channel.BatchTotQueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<FcubService.BatchTotQueryResponse> BatchTotQueryAsync(string BatchTotQuery)
        {
            FcubService.BatchTotQueryRequest inValue = new FcubService.BatchTotQueryRequest();
            inValue.BatchTotQuery = BatchTotQuery;
            return ((FcubService.FCUBSDEServiceSEI)(this)).BatchTotQueryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FcubService.BatchTotDeleteResponse> FcubService.FCUBSDEServiceSEI.BatchTotDeleteAsync(FcubService.BatchTotDeleteRequest request)
        {
            return base.Channel.BatchTotDeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<FcubService.BatchTotDeleteResponse> BatchTotDeleteAsync(string BatchTotDelete)
        {
            FcubService.BatchTotDeleteRequest inValue = new FcubService.BatchTotDeleteRequest();
            inValue.BatchTotDelete = BatchTotDelete;
            return ((FcubService.FCUBSDEServiceSEI)(this)).BatchTotDeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FcubService.BatchTotAuthResponse> FcubService.FCUBSDEServiceSEI.BatchTotAuthAsync(FcubService.BatchTotAuthRequest request)
        {
            return base.Channel.BatchTotAuthAsync(request);
        }
        
        public System.Threading.Tasks.Task<FcubService.BatchTotAuthResponse> BatchTotAuthAsync(string BatchTotAuth)
        {
            FcubService.BatchTotAuthRequest inValue = new FcubService.BatchTotAuthRequest();
            inValue.BatchTotAuth = BatchTotAuth;
            return ((FcubService.FCUBSDEServiceSEI)(this)).BatchTotAuthAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FcubService.BatchAuthorizeResponse> FcubService.FCUBSDEServiceSEI.BatchAuthorizeAsync(FcubService.BatchAuthorizeRequest request)
        {
            return base.Channel.BatchAuthorizeAsync(request);
        }
        
        public System.Threading.Tasks.Task<FcubService.BatchAuthorizeResponse> BatchAuthorizeAsync(string BatchAuthorize)
        {
            FcubService.BatchAuthorizeRequest inValue = new FcubService.BatchAuthorizeRequest();
            inValue.BatchAuthorize = BatchAuthorize;
            return ((FcubService.FCUBSDEServiceSEI)(this)).BatchAuthorizeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FcubService.BatchAuthQryResponse> FcubService.FCUBSDEServiceSEI.BatchAuthQryAsync(FcubService.BatchAuthQryRequest request)
        {
            return base.Channel.BatchAuthQryAsync(request);
        }
        
        public System.Threading.Tasks.Task<FcubService.BatchAuthQryResponse> BatchAuthQryAsync(string BatchAuthQry)
        {
            FcubService.BatchAuthQryRequest inValue = new FcubService.BatchAuthQryRequest();
            inValue.BatchAuthQry = BatchAuthQry;
            return ((FcubService.FCUBSDEServiceSEI)(this)).BatchAuthQryAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FCUBSDEServiceSEI))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FCUBSDEServiceSEI))
            {
                return new System.ServiceModel.EndpointAddress(ApplicationConstant.FcubService);
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return FCUBSDEServiceSEIClient.GetBindingForEndpoint(EndpointConfiguration.FCUBSDEServiceSEI);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return FCUBSDEServiceSEIClient.GetEndpointAddress(EndpointConfiguration.FCUBSDEServiceSEI);
        }
        
        public enum EndpointConfiguration
        {
            
            FCUBSDEServiceSEI,
        }
    }
}
