//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityService
{
    using EasyAssetManagerCore.Model.CommonModel;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDetails", Namespace="http://tempuri.org/")]
    public partial class UserDetails : object
    {
        
        private SecurityService.UserInfo[] UserInfoListField;
        
        private string StatusCodeField;
        
        private string StatusDescField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SecurityService.UserInfo[] UserInfoList
        {
            get
            {
                return this.UserInfoListField;
            }
            set
            {
                this.UserInfoListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StatusDesc
        {
            get
            {
                return this.StatusDescField;
            }
            set
            {
                this.StatusDescField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://tempuri.org/")]
    public partial class UserInfo : object
    {
        
        private string UserIdField;
        
        private string UserNameField;
        
        private string EmployeeIdField;
        
        private string EmailField;
        
        private string MobileField;
        
        private string ActiveField;
        
        private string LoggedInField;
        
        private string OtpReqField;
        
        private string LockedField;
        
        private string BranchCodeField;
        
        private string BranchNameField;
        
        private string DivisionCodeField;
        
        private string DivisionNameField;
        
        private string DepartmentCodeField;
        
        private string DepartmentNameField;
        
        private string DesignationCodeField;
        
        private string DesignationNameField;
        
        private string CompanyNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EmployeeId
        {
            get
            {
                return this.EmployeeIdField;
            }
            set
            {
                this.EmployeeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Mobile
        {
            get
            {
                return this.MobileField;
            }
            set
            {
                this.MobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string LoggedIn
        {
            get
            {
                return this.LoggedInField;
            }
            set
            {
                this.LoggedInField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string OtpReq
        {
            get
            {
                return this.OtpReqField;
            }
            set
            {
                this.OtpReqField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Locked
        {
            get
            {
                return this.LockedField;
            }
            set
            {
                this.LockedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string BranchCode
        {
            get
            {
                return this.BranchCodeField;
            }
            set
            {
                this.BranchCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string BranchName
        {
            get
            {
                return this.BranchNameField;
            }
            set
            {
                this.BranchNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string DivisionCode
        {
            get
            {
                return this.DivisionCodeField;
            }
            set
            {
                this.DivisionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string DivisionName
        {
            get
            {
                return this.DivisionNameField;
            }
            set
            {
                this.DivisionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string DepartmentCode
        {
            get
            {
                return this.DepartmentCodeField;
            }
            set
            {
                this.DepartmentCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string DepartmentName
        {
            get
            {
                return this.DepartmentNameField;
            }
            set
            {
                this.DepartmentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string DesignationCode
        {
            get
            {
                return this.DesignationCodeField;
            }
            set
            {
                this.DesignationCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string DesignationName
        {
            get
            {
                return this.DesignationNameField;
            }
            set
            {
                this.DesignationNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string CompanyName
        {
            get
            {
                return this.CompanyNameField;
            }
            set
            {
                this.CompanyNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogoutDetails", Namespace="http://tempuri.org/")]
    public partial class LogoutDetails : object
    {
        
        private string StatusCodeField;
        
        private string StatusDescField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusDesc
        {
            get
            {
                return this.StatusDescField;
            }
            set
            {
                this.StatusDescField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectDetails", Namespace="http://tempuri.org/")]
    public partial class ProjectDetails : object
    {
        
        private SecurityService.ProjectInfo[] ProjectInfoListField;
        
        private string StatusCodeField;
        
        private string StatusDescField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SecurityService.ProjectInfo[] ProjectInfoList
        {
            get
            {
                return this.ProjectInfoListField;
            }
            set
            {
                this.ProjectInfoListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusDesc
        {
            get
            {
                return this.StatusDescField;
            }
            set
            {
                this.StatusDescField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectInfo", Namespace="http://tempuri.org/")]
    public partial class ProjectInfo : object
    {
        
        private string projIdField;
        
        private string projNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string projId
        {
            get
            {
                return this.projIdField;
            }
            set
            {
                this.projIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string projName
        {
            get
            {
                return this.projNameField;
            }
            set
            {
                this.projNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModuleDetails", Namespace="http://tempuri.org/")]
    public partial class ModuleDetails : object
    {
        
        private SecurityService.ModuleInfo[] ModuleInfoListField;
        
        private string StatusCodeField;
        
        private string StatusDescField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SecurityService.ModuleInfo[] ModuleInfoList
        {
            get
            {
                return this.ModuleInfoListField;
            }
            set
            {
                this.ModuleInfoListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusDesc
        {
            get
            {
                return this.StatusDescField;
            }
            set
            {
                this.StatusDescField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModuleInfo", Namespace="http://tempuri.org/")]
    public partial class ModuleInfo : object
    {
        
        private string modIdField;
        
        private string modNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string modId
        {
            get
            {
                return this.modIdField;
            }
            set
            {
                this.modIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string modName
        {
            get
            {
                return this.modNameField;
            }
            set
            {
                this.modNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuDetails", Namespace="http://tempuri.org/")]
    public partial class MenuDetails : object
    {
        
        private SecurityService.MenuInfo[] MenuInfoListField;
        
        private string StatusCodeField;
        
        private string StatusDescField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SecurityService.MenuInfo[] MenuInfoList
        {
            get
            {
                return this.MenuInfoListField;
            }
            set
            {
                this.MenuInfoListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusDesc
        {
            get
            {
                return this.StatusDescField;
            }
            set
            {
                this.StatusDescField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuInfo", Namespace="http://tempuri.org/")]
    public partial class MenuInfo : object
    {
        
        private string ScrIdField;
        
        private string ModIdField;
        
        private string ScrNameField;
        
        private string ScrLinkField;
        
        private string DescpField;
        
        private string RoleField;
        
        private string ScrParentIdField;
        
        private string ScrseqNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ScrId
        {
            get
            {
                return this.ScrIdField;
            }
            set
            {
                this.ScrIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ModId
        {
            get
            {
                return this.ModIdField;
            }
            set
            {
                this.ModIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ScrName
        {
            get
            {
                return this.ScrNameField;
            }
            set
            {
                this.ScrNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ScrLink
        {
            get
            {
                return this.ScrLinkField;
            }
            set
            {
                this.ScrLinkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Descp
        {
            get
            {
                return this.DescpField;
            }
            set
            {
                this.DescpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Role
        {
            get
            {
                return this.RoleField;
            }
            set
            {
                this.RoleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ScrParentId
        {
            get
            {
                return this.ScrParentIdField;
            }
            set
            {
                this.ScrParentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ScrseqNo
        {
            get
            {
                return this.ScrseqNoField;
            }
            set
            {
                this.ScrseqNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InterfaceDetails", Namespace="http://tempuri.org/")]
    public partial class InterfaceDetails : object
    {
        
        private SecurityService.InterfaceInfo[] InterfaceInfoListField;
        
        private string StatusCodeField;
        
        private string StatusDescField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SecurityService.InterfaceInfo[] InterfaceInfoList
        {
            get
            {
                return this.InterfaceInfoListField;
            }
            set
            {
                this.InterfaceInfoListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusDesc
        {
            get
            {
                return this.StatusDescField;
            }
            set
            {
                this.StatusDescField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InterfaceInfo", Namespace="http://tempuri.org/")]
    public partial class InterfaceInfo : object
    {
        
        private string ScrIdField;
        
        private string ModIdField;
        
        private string ScrNameField;
        
        private string DescpField;
        
        private string ScrParentIdField;
        
        private string ScrseqNoField;
        
        private string ScrTypeField;
        
        private string CanUpdateField;
        
        private string CanDeleteField;
        
        private string CanViewField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ScrId
        {
            get
            {
                return this.ScrIdField;
            }
            set
            {
                this.ScrIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ModId
        {
            get
            {
                return this.ModIdField;
            }
            set
            {
                this.ModIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ScrName
        {
            get
            {
                return this.ScrNameField;
            }
            set
            {
                this.ScrNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Descp
        {
            get
            {
                return this.DescpField;
            }
            set
            {
                this.DescpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ScrParentId
        {
            get
            {
                return this.ScrParentIdField;
            }
            set
            {
                this.ScrParentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ScrseqNo
        {
            get
            {
                return this.ScrseqNoField;
            }
            set
            {
                this.ScrseqNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ScrType
        {
            get
            {
                return this.ScrTypeField;
            }
            set
            {
                this.ScrTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CanUpdate
        {
            get
            {
                return this.CanUpdateField;
            }
            set
            {
                this.CanUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string CanDelete
        {
            get
            {
                return this.CanDeleteField;
            }
            set
            {
                this.CanDeleteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string CanView
        {
            get
            {
                return this.CanViewField;
            }
            set
            {
                this.CanViewField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SecurityService.SecurityServicesSoap")]
    public interface SecurityServicesSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<SecurityService.AuthenticateUserResponse> AuthenticateUserAsync(SecurityService.AuthenticateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogoutUser", ReplyAction="*")]
        System.Threading.Tasks.Task<SecurityService.LogoutUserResponse> LogoutUserAsync(SecurityService.LogoutUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserProjects", ReplyAction="*")]
        System.Threading.Tasks.Task<SecurityService.GetUserProjectsResponse> GetUserProjectsAsync(SecurityService.GetUserProjectsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserModules", ReplyAction="*")]
        System.Threading.Tasks.Task<SecurityService.GetUserModulesResponse> GetUserModulesAsync(SecurityService.GetUserModulesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserMenu", ReplyAction="*")]
        System.Threading.Tasks.Task<SecurityService.GetUserMenuResponse> GetUserMenuAsync(SecurityService.GetUserMenuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserInterface", ReplyAction="*")]
        System.Threading.Tasks.Task<SecurityService.GetUserInterfaceResponse> GetUserInterfaceAsync(SecurityService.GetUserInterfaceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<SecurityService.GetUserInfoResponse> GetUserInfoAsync(SecurityService.GetUserInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUser", Namespace="http://tempuri.org/", Order=0)]
        public SecurityService.AuthenticateUserRequestBody Body;
        
        public AuthenticateUserRequest()
        {
        }
        
        public AuthenticateUserRequest(SecurityService.AuthenticateUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string projectId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string clientIp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string clientSession;
        
        public AuthenticateUserRequestBody()
        {
        }
        
        public AuthenticateUserRequestBody(string userId, string password, string projectId, string clientIp, string clientSession)
        {
            this.userId = userId;
            this.password = password;
            this.projectId = projectId;
            this.clientIp = clientIp;
            this.clientSession = clientSession;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public SecurityService.AuthenticateUserResponseBody Body;
        
        public AuthenticateUserResponse()
        {
        }
        
        public AuthenticateUserResponse(SecurityService.AuthenticateUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SecurityService.UserDetails AuthenticateUserResult;
        
        public AuthenticateUserResponseBody()
        {
        }
        
        public AuthenticateUserResponseBody(SecurityService.UserDetails AuthenticateUserResult)
        {
            this.AuthenticateUserResult = AuthenticateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutUser", Namespace="http://tempuri.org/", Order=0)]
        public SecurityService.LogoutUserRequestBody Body;
        
        public LogoutUserRequest()
        {
        }
        
        public LogoutUserRequest(SecurityService.LogoutUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string projectId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string clientIp;
        
        public LogoutUserRequestBody()
        {
        }
        
        public LogoutUserRequestBody(string userId, string projectId, string clientIp)
        {
            this.userId = userId;
            this.projectId = projectId;
            this.clientIp = clientIp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public SecurityService.LogoutUserResponseBody Body;
        
        public LogoutUserResponse()
        {
        }
        
        public LogoutUserResponse(SecurityService.LogoutUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SecurityService.LogoutDetails LogoutUserResult;
        
        public LogoutUserResponseBody()
        {
        }
        
        public LogoutUserResponseBody(SecurityService.LogoutDetails LogoutUserResult)
        {
            this.LogoutUserResult = LogoutUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserProjectsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserProjects", Namespace="http://tempuri.org/", Order=0)]
        public SecurityService.GetUserProjectsRequestBody Body;
        
        public GetUserProjectsRequest()
        {
        }
        
        public GetUserProjectsRequest(SecurityService.GetUserProjectsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserProjectsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetUserProjectsRequestBody()
        {
        }
        
        public GetUserProjectsRequestBody(string userId, string password)
        {
            this.userId = userId;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserProjectsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserProjectsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SecurityService.GetUserProjectsResponseBody Body;
        
        public GetUserProjectsResponse()
        {
        }
        
        public GetUserProjectsResponse(SecurityService.GetUserProjectsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserProjectsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SecurityService.ProjectDetails GetUserProjectsResult;
        
        public GetUserProjectsResponseBody()
        {
        }
        
        public GetUserProjectsResponseBody(SecurityService.ProjectDetails GetUserProjectsResult)
        {
            this.GetUserProjectsResult = GetUserProjectsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserModulesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserModules", Namespace="http://tempuri.org/", Order=0)]
        public SecurityService.GetUserModulesRequestBody Body;
        
        public GetUserModulesRequest()
        {
        }
        
        public GetUserModulesRequest(SecurityService.GetUserModulesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserModulesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string projectId;
        
        public GetUserModulesRequestBody()
        {
        }
        
        public GetUserModulesRequestBody(string userId, string password, string projectId)
        {
            this.userId = userId;
            this.password = password;
            this.projectId = projectId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserModulesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserModulesResponse", Namespace="http://tempuri.org/", Order=0)]
        public SecurityService.GetUserModulesResponseBody Body;
        
        public GetUserModulesResponse()
        {
        }
        
        public GetUserModulesResponse(SecurityService.GetUserModulesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserModulesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SecurityService.ModuleDetails GetUserModulesResult;
        
        public GetUserModulesResponseBody()
        {
        }
        
        public GetUserModulesResponseBody(SecurityService.ModuleDetails GetUserModulesResult)
        {
            this.GetUserModulesResult = GetUserModulesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserMenuRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserMenu", Namespace="http://tempuri.org/", Order=0)]
        public SecurityService.GetUserMenuRequestBody Body;
        
        public GetUserMenuRequest()
        {
        }
        
        public GetUserMenuRequest(SecurityService.GetUserMenuRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserMenuRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string modid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string projectId;
        
        public GetUserMenuRequestBody()
        {
        }
        
        public GetUserMenuRequestBody(string userId, string password, string modid, string projectId)
        {
            this.userId = userId;
            this.password = password;
            this.modid = modid;
            this.projectId = projectId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserMenuResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserMenuResponse", Namespace="http://tempuri.org/", Order=0)]
        public SecurityService.GetUserMenuResponseBody Body;
        
        public GetUserMenuResponse()
        {
        }
        
        public GetUserMenuResponse(SecurityService.GetUserMenuResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserMenuResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SecurityService.MenuDetails GetUserMenuResult;
        
        public GetUserMenuResponseBody()
        {
        }
        
        public GetUserMenuResponseBody(SecurityService.MenuDetails GetUserMenuResult)
        {
            this.GetUserMenuResult = GetUserMenuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInterfaceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInterface", Namespace="http://tempuri.org/", Order=0)]
        public SecurityService.GetUserInterfaceRequestBody Body;
        
        public GetUserInterfaceRequest()
        {
        }
        
        public GetUserInterfaceRequest(SecurityService.GetUserInterfaceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserInterfaceRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string scrId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string interfaceType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string modid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string projectId;
        
        public GetUserInterfaceRequestBody()
        {
        }
        
        public GetUserInterfaceRequestBody(string userId, string password, string scrId, string interfaceType, string modid, string projectId)
        {
            this.userId = userId;
            this.password = password;
            this.scrId = scrId;
            this.interfaceType = interfaceType;
            this.modid = modid;
            this.projectId = projectId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInterfaceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInterfaceResponse", Namespace="http://tempuri.org/", Order=0)]
        public SecurityService.GetUserInterfaceResponseBody Body;
        
        public GetUserInterfaceResponse()
        {
        }
        
        public GetUserInterfaceResponse(SecurityService.GetUserInterfaceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserInterfaceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SecurityService.InterfaceDetails GetUserInterfaceResult;
        
        public GetUserInterfaceResponseBody()
        {
        }
        
        public GetUserInterfaceResponseBody(SecurityService.InterfaceDetails GetUserInterfaceResult)
        {
            this.GetUserInterfaceResult = GetUserInterfaceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInfo", Namespace="http://tempuri.org/", Order=0)]
        public SecurityService.GetUserInfoRequestBody Body;
        
        public GetUserInfoRequest()
        {
        }
        
        public GetUserInfoRequest(SecurityService.GetUserInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserInfoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string projectId;
        
        public GetUserInfoRequestBody()
        {
        }
        
        public GetUserInfoRequestBody(string userId, string password, string projectId)
        {
            this.userId = userId;
            this.password = password;
            this.projectId = projectId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public SecurityService.GetUserInfoResponseBody Body;
        
        public GetUserInfoResponse()
        {
        }
        
        public GetUserInfoResponse(SecurityService.GetUserInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SecurityService.UserDetails GetUserInfoResult;
        
        public GetUserInfoResponseBody()
        {
        }
        
        public GetUserInfoResponseBody(SecurityService.UserDetails GetUserInfoResult)
        {
            this.GetUserInfoResult = GetUserInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface SecurityServicesSoapChannel : SecurityService.SecurityServicesSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class SecurityServicesSoapClient : System.ServiceModel.ClientBase<SecurityService.SecurityServicesSoap>, SecurityService.SecurityServicesSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SecurityServicesSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SecurityServicesSoapClient.GetBindingForEndpoint(endpointConfiguration), SecurityServicesSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SecurityServicesSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SecurityServicesSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SecurityServicesSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SecurityServicesSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SecurityServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SecurityService.AuthenticateUserResponse> SecurityService.SecurityServicesSoap.AuthenticateUserAsync(SecurityService.AuthenticateUserRequest request)
        {
            return base.Channel.AuthenticateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<SecurityService.AuthenticateUserResponse> AuthenticateUserAsync(string userId, string password, string projectId, string clientIp, string clientSession)
        {
            SecurityService.AuthenticateUserRequest inValue = new SecurityService.AuthenticateUserRequest();
            inValue.Body = new SecurityService.AuthenticateUserRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.projectId = projectId;
            inValue.Body.clientIp = clientIp;
            inValue.Body.clientSession = clientSession;
            return ((SecurityService.SecurityServicesSoap)(this)).AuthenticateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SecurityService.LogoutUserResponse> SecurityService.SecurityServicesSoap.LogoutUserAsync(SecurityService.LogoutUserRequest request)
        {
            return base.Channel.LogoutUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<SecurityService.LogoutUserResponse> LogoutUserAsync(string userId, string projectId, string clientIp)
        {
            SecurityService.LogoutUserRequest inValue = new SecurityService.LogoutUserRequest();
            inValue.Body = new SecurityService.LogoutUserRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.projectId = projectId;
            inValue.Body.clientIp = clientIp;
            return ((SecurityService.SecurityServicesSoap)(this)).LogoutUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SecurityService.GetUserProjectsResponse> SecurityService.SecurityServicesSoap.GetUserProjectsAsync(SecurityService.GetUserProjectsRequest request)
        {
            return base.Channel.GetUserProjectsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SecurityService.GetUserProjectsResponse> GetUserProjectsAsync(string userId, string password)
        {
            SecurityService.GetUserProjectsRequest inValue = new SecurityService.GetUserProjectsRequest();
            inValue.Body = new SecurityService.GetUserProjectsRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            return ((SecurityService.SecurityServicesSoap)(this)).GetUserProjectsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SecurityService.GetUserModulesResponse> SecurityService.SecurityServicesSoap.GetUserModulesAsync(SecurityService.GetUserModulesRequest request)
        {
            return base.Channel.GetUserModulesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SecurityService.GetUserModulesResponse> GetUserModulesAsync(string userId, string password, string projectId)
        {
            SecurityService.GetUserModulesRequest inValue = new SecurityService.GetUserModulesRequest();
            inValue.Body = new SecurityService.GetUserModulesRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.projectId = projectId;
            return ((SecurityService.SecurityServicesSoap)(this)).GetUserModulesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SecurityService.GetUserMenuResponse> SecurityService.SecurityServicesSoap.GetUserMenuAsync(SecurityService.GetUserMenuRequest request)
        {
            return base.Channel.GetUserMenuAsync(request);
        }
        
        public System.Threading.Tasks.Task<SecurityService.GetUserMenuResponse> GetUserMenuAsync(string userId, string password, string modid, string projectId)
        {
            SecurityService.GetUserMenuRequest inValue = new SecurityService.GetUserMenuRequest();
            inValue.Body = new SecurityService.GetUserMenuRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.modid = modid;
            inValue.Body.projectId = projectId;
            return ((SecurityService.SecurityServicesSoap)(this)).GetUserMenuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SecurityService.GetUserInterfaceResponse> SecurityService.SecurityServicesSoap.GetUserInterfaceAsync(SecurityService.GetUserInterfaceRequest request)
        {
            return base.Channel.GetUserInterfaceAsync(request);
        }
        
        public System.Threading.Tasks.Task<SecurityService.GetUserInterfaceResponse> GetUserInterfaceAsync(string userId, string password, string scrId, string interfaceType, string modid, string projectId)
        {
            SecurityService.GetUserInterfaceRequest inValue = new SecurityService.GetUserInterfaceRequest();
            inValue.Body = new SecurityService.GetUserInterfaceRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.scrId = scrId;
            inValue.Body.interfaceType = interfaceType;
            inValue.Body.modid = modid;
            inValue.Body.projectId = projectId;
            return ((SecurityService.SecurityServicesSoap)(this)).GetUserInterfaceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SecurityService.GetUserInfoResponse> SecurityService.SecurityServicesSoap.GetUserInfoAsync(SecurityService.GetUserInfoRequest request)
        {
            return base.Channel.GetUserInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SecurityService.GetUserInfoResponse> GetUserInfoAsync(string userId, string password, string projectId)
        {
            SecurityService.GetUserInfoRequest inValue = new SecurityService.GetUserInfoRequest();
            inValue.Body = new SecurityService.GetUserInfoRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.projectId = projectId;
            return ((SecurityService.SecurityServicesSoap)(this)).GetUserInfoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SecurityServicesSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SecurityServicesSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SecurityServicesSoap))
            {
                return new System.ServiceModel.EndpointAddress(ApplicationConstant.CardService);
            }
            if ((endpointConfiguration == EndpointConfiguration.SecurityServicesSoap12))
            {
                return new System.ServiceModel.EndpointAddress(ApplicationConstant.CardService);
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
            
        }
        
        public enum EndpointConfiguration
        {
            
            SecurityServicesSoap,
            
            SecurityServicesSoap12,
        }
    }
}
